"""
db/models/roadmap.py
========================
Career Roadmap persistence (§4.3). A `Roadmap` belongs to a user and target
role, and contains an ordered list of `RoadmapMilestone`s (timeline phases).
Each milestone references a set of `RoadmapSkill` rows tracking per-skill
content (resources, study material, practice activities — all generated by
the Roadmap agent team) and the user's own progress status.
"""

import uuid

from sqlalchemy import JSON, Float, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.db.models.mixins import OrderableMixin, TimestampMixin, UUIDPrimaryKeyMixin


class Roadmap(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "roadmaps"

    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    target_role: Mapped[str] = mapped_column(String(255))
    pace: Mapped[str] = mapped_column(String(20), default="normal")  # fast | normal | thorough
    starting_skill_level: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # Snapshot of the personalization inputs used at generation time.
    personalization_inputs: Mapped[dict] = mapped_column(JSON, default=dict)

    user: Mapped["User"] = relationship(back_populates="roadmaps")  # noqa: F821
    milestones: Mapped[list["RoadmapMilestone"]] = relationship(
        back_populates="roadmap", cascade="all, delete-orphan", order_by="RoadmapMilestone.order_index"
    )


class RoadmapMilestone(UUIDPrimaryKeyMixin, OrderableMixin, Base):
    __tablename__ = "roadmap_milestones"

    roadmap_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("roadmaps.id", ondelete="CASCADE"))
    title: Mapped[str] = mapped_column(String(255))  # e.g. "Month 0-3: Foundations"
    timeframe_label: Mapped[str | None] = mapped_column(String(100), nullable=True)

    roadmap: Mapped["Roadmap"] = relationship(back_populates="milestones")
    skills: Mapped[list["RoadmapSkill"]] = relationship(
        back_populates="milestone", cascade="all, delete-orphan", order_by="RoadmapSkill.order_index"
    )


class RoadmapSkill(UUIDPrimaryKeyMixin, OrderableMixin, Base):
    __tablename__ = "roadmap_skills"

    milestone_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("roadmap_milestones.id", ondelete="CASCADE")
    )
    skill_name: Mapped[str] = mapped_column(String(255))
    importance: Mapped[str | None] = mapped_column(String(20), nullable=True)  # critical|high|medium|nice-to-have
    estimated_hours: Mapped[float | None] = mapped_column(Float, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="not_started")  # not_started|in_progress|completed

    # Generated content blobs — produced once by ResourceFinderAgent /
    # StudyMaterialAgent / PracticeGeneratorAgent and cached here so re-opening
    # a skill's modal doesn't re-trigger an LLM call (see CostMonitorAgent).
    resources: Mapped[list] = mapped_column(JSON, default=list)
    study_material: Mapped[dict] = mapped_column(JSON, default=dict)
    practice_activities: Mapped[dict] = mapped_column(JSON, default=dict)
    lateral_connections: Mapped[list] = mapped_column(JSON, default=list)  # GraphRAG-derived related skills

    milestone: Mapped["RoadmapMilestone"] = relationship(back_populates="skills")
