"""Document-library input-state binding (004E-E2.3C Prompt 3 — Finding F1).

Runtime evidence (not a script string-scan): the 004E-F generation call graph
reaches the document library —

    audit_generated_pack
      -> build_source_ladder_status(job)
        -> find_role_study_documents(role_title)
          -> find_role_pack  -> reads documents/indexes/role_index.json
          -> _load_saved_questions -> reads the matched pack's
             metadata.json / structured_content.json / *_study_material.md

so document-library state can affect generated bytes. Before F1 it was OUTSIDE
run-context identity (documents/ excluded from the fingerprint), a realistic
false-current path. These tests bind exactly the generation-relevant inputs
(indexes + consumed interview-pack json/md), never PDFs or non-consumed dirs,
and never document contents.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.agents.job_search.quality.run_manifest import (
    REASON_DOCUMENT_LIBRARY_CHANGED,
    STATUS_CURRENT,
    STATUS_STALE,
    build_generation_run_manifest,
    classify_artifact_evidence,
    compute_document_library_fingerprint,
    context_digest_of,
    current_run_context,
)

REPO_ROOT = Path(__file__).resolve().parents[5]


def _make_library(root: Path) -> None:
    """A minimal documents/ mirror: indexes + one interview pack (json/md) + a
    non-consumed PDF and non-consumed sibling dirs."""
    (root / "indexes").mkdir(parents=True)
    (root / "indexes" / "role_index.json").write_text(
        json.dumps({"graphic designer": "arts_media/graphic_designer"}), encoding="utf-8"
    )
    (root / "indexes" / "skill_index.json").write_text("{}", encoding="utf-8")
    pack = root / "interview_packs" / "arts_media" / "graphic_designer"
    pack.mkdir(parents=True)
    (pack / "metadata.json").write_text(json.dumps({"role": "Graphic Designer"}), encoding="utf-8")
    (pack / "structured_content.json").write_text(json.dumps({"questions": [1]}), encoding="utf-8")
    (pack / "graphic_designer_study_material.md").write_text("# study\noriginal\n", encoding="utf-8")
    (pack / "graphic_designer_interview_pack.pdf").write_bytes(b"%PDF-1.4 original")
    # Non-consumed sibling directories (must not affect the fingerprint).
    (root / "source_materials").mkdir()
    (root / "source_materials" / "cv.pdf").write_bytes(b"%PDF private cv")
    (root / "exports").mkdir()
    (root / "exports" / "export.md").write_text("export", encoding="utf-8")


# --- T1 — relevant index change -------------------------------------------------

def test_t1_index_change_changes_fingerprint(tmp_path: Path) -> None:
    root = tmp_path / "documents"
    _make_library(root)
    before = compute_document_library_fingerprint(root)
    (root / "indexes" / "role_index.json").write_text(
        json.dumps({"graphic designer": "arts_media/graphic_designer", "new role": "x/y"}),
        encoding="utf-8",
    )
    assert compute_document_library_fingerprint(root) != before


# --- T2 — matched role-pack content change --------------------------------------

def test_t2_matched_pack_content_change_changes_fingerprint(tmp_path: Path) -> None:
    root = tmp_path / "documents"
    _make_library(root)
    before = compute_document_library_fingerprint(root)
    pack = root / "interview_packs" / "arts_media" / "graphic_designer"
    (pack / "structured_content.json").write_text(json.dumps({"questions": [1, 2, 3]}), encoding="utf-8")
    assert compute_document_library_fingerprint(root) != before
    # A consumed markdown change is also caught.
    before2 = compute_document_library_fingerprint(root)
    (pack / "graphic_designer_study_material.md").write_text("# study\nEDITED\n", encoding="utf-8")
    assert compute_document_library_fingerprint(root) != before2


# --- T3 — unrelated / non-consumed change does NOT drift the fingerprint --------

def test_t3_noncomsumed_files_do_not_change_fingerprint(tmp_path: Path) -> None:
    """Runtime evidence proves PDFs and the source_materials/exports dirs are not
    consumed during generation, so editing them must not invalidate evidence
    (prevents broad over-hashing of the personal document tree)."""
    root = tmp_path / "documents"
    _make_library(root)
    before = compute_document_library_fingerprint(root)
    # Edit a PDF inside a consumed pack — not consumed at generation time.
    pack = root / "interview_packs" / "arts_media" / "graphic_designer"
    (pack / "graphic_designer_interview_pack.pdf").write_bytes(b"%PDF-1.4 TAMPERED")
    # Edit a private CV PDF and an export in non-consumed sibling dirs.
    (root / "source_materials" / "cv.pdf").write_bytes(b"%PDF different private cv")
    (root / "exports" / "export.md").write_text("changed export", encoding="utf-8")
    assert compute_document_library_fingerprint(root) == before


# --- Path-independence correction: identical corpus at different absolute roots
#     MUST fingerprint identically (a copied library is not "stale"). -----------

def test_identical_corpus_at_different_roots_has_same_fingerprint(tmp_path: Path) -> None:
    root_a = tmp_path / "libA" / "documents"
    root_b = tmp_path / "var_folders_xxxx" / "documents"
    _make_library(root_a)
    _make_library(root_b)  # byte-identical relevant corpus, different absolute root
    assert compute_document_library_fingerprint(root_a) == compute_document_library_fingerprint(
        root_b
    )


def test_relevant_file_added_changes_fingerprint(tmp_path: Path) -> None:
    root = tmp_path / "documents"
    _make_library(root)
    before = compute_document_library_fingerprint(root)
    pack = root / "interview_packs" / "arts_media" / "graphic_designer"
    (pack / "sources.json").write_text(json.dumps({"src": 1}), encoding="utf-8")
    assert compute_document_library_fingerprint(root) != before


def test_relevant_file_removed_changes_fingerprint(tmp_path: Path) -> None:
    root = tmp_path / "documents"
    _make_library(root)
    before = compute_document_library_fingerprint(root)
    (root / "interview_packs" / "arts_media" / "graphic_designer" / "metadata.json").unlink()
    assert compute_document_library_fingerprint(root) != before


def test_relevant_relative_path_rename_changes_fingerprint(tmp_path: Path) -> None:
    root = tmp_path / "documents"
    _make_library(root)
    before = compute_document_library_fingerprint(root)
    pack = root / "interview_packs" / "arts_media" / "graphic_designer"
    (pack / "structured_content.json").rename(pack / "renamed_content.json")
    assert compute_document_library_fingerprint(root) != before


# --- T5 — no document library (deterministic) -----------------------------------

def test_t5_missing_library_is_deterministic(tmp_path: Path) -> None:
    missing = tmp_path / "nope"
    fp1 = compute_document_library_fingerprint(missing)
    fp2 = compute_document_library_fingerprint(missing)
    assert fp1 == fp2 and len(fp1) == 16
    # An empty (but existing) library is distinct from a populated one.
    empty = tmp_path / "empty_docs"
    empty.mkdir()
    populated = tmp_path / "populated" / "documents"
    _make_library(populated)
    assert compute_document_library_fingerprint(empty) != compute_document_library_fingerprint(
        populated
    )


# --- T6 — corrected dependency evidence (replaces the false T11 string-scan) -----

def test_t6_generation_call_graph_reads_document_library() -> None:
    """Dependency-aware proof that generation reads documents/ (the premise the
    old script-string-scan T11 got wrong)."""
    import builtins  # noqa: F401
    reads: set[str] = set()
    _rt = Path.read_text

    def traced(self, *a, **k):  # type: ignore[no-untyped-def]
        s = str(self)
        if "/documents/" in s:
            reads.add(s.split("/documents/", 1)[1])
        return _rt(self, *a, **k)

    Path.read_text = traced  # type: ignore[assignment]
    try:
        from app.agents.job_search.knowledge.source_ladder import build_source_ladder_status

        build_source_ladder_status({"title": "Graphic Designer"})
    finally:
        Path.read_text = _rt  # type: ignore[assignment]
    # Generation genuinely reads the document library (the premise the old
    # script-string-scan T11 got wrong)...
    assert reads, "generation must consume document-library files"
    # ...and every consumed file falls within the BOUND fingerprint scope
    # (indexes/ or interview_packs/, json/md only) — so the binding covers the
    # real dependency and nothing consumed escapes it.
    for rel in reads:
        assert rel.startswith(("indexes/", "interview_packs/")), rel
        assert rel.endswith((".json", ".md")), rel


# --- Run-context integration ----------------------------------------------------

def test_manifest_carries_document_library_fingerprint() -> None:
    manifest = build_generation_run_manifest(REPO_ROOT)
    assert manifest.get("document_library_fingerprint")
    assert len(manifest["document_library_fingerprint"]) == 16


def test_document_fingerprint_participates_in_context_digest() -> None:
    manifest = build_generation_run_manifest(REPO_ROOT)
    other = dict(manifest)
    other["document_library_fingerprint"] = "0" * 16
    assert context_digest_of(manifest) != context_digest_of(other)


def test_document_library_change_marks_stored_artifact_stale() -> None:
    manifest = build_generation_run_manifest(REPO_ROOT)
    context = current_run_context(REPO_ROOT)
    # Same state -> current.
    assert classify_artifact_evidence(manifest, context)["status"] == STATUS_CURRENT
    # Different document-library fingerprint -> stale (old evidence not current).
    drifted = dict(context)
    drifted["document_library_fingerprint"] = "deadbeefdeadbeef"
    result = classify_artifact_evidence(manifest, drifted)
    assert result["status"] == STATUS_STALE
    assert REASON_DOCUMENT_LIBRARY_CHANGED in result["reasons"]
