"""initial schema — create every table from the ORM models

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-01

Why this migration exists
-------------------------
Before this file, `backend/app/db/migrations/versions/` was empty, so
`alembic upgrade head` on a brand-new database did nothing and no tables were
ever created — every database-backed feature failed on first use (README §36
item 1).

This is a *baseline* migration: instead of hand-writing `op.create_table(...)`
for all ~30 tables, it builds the whole schema directly from the SQLAlchemy
models' metadata. Alembic's `env.py` already imports every model
(`from app.db.models import *`), so by the time this runs `Base.metadata` is
fully populated and describes the entire schema — including newer columns such
as `saved_jobs.status`.

`create_all` / `drop_all` use `checkfirst=True`, so re-running is safe.

Future schema changes should be normal autogenerated migrations that set their
`down_revision` to this one.
"""

from alembic import op

# Importing the models package registers every table on Base.metadata. env.py
# already does this, but importing here too keeps the migration correct even if
# it is ever executed in isolation.
import app.db.models  # noqa: F401  (imported for its table-registration side effects)
from app.db.base import Base

# --- Alembic identifiers ---------------------------------------------------
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create all tables defined by the ORM models."""
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Drop all tables defined by the ORM models."""
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
